--- 
- hosts: db
  vars_files:
    - configurable_vars.yml
    - init_vars.yml
  become: yes
  name: Setup HA postgresql on the given DB servers
  tasks:
    - name: debug print
      debug: 
        msg: "cluster_master: {{ cluster_master }} cluster_fqdns: {{cluster_fqdns }}"
      tags: debug
    - include: tasks/base_packages.yml
    - include: tasks/nfs_config.yml
      tags: nfs
    - include: tasks/firewall.yml
      tags: firewall
    - include: tasks/db_init.yml
      tags: db
    - include: tasks/cluster_init.yml 
      tags: cluster
