    - name: Add base repositories
      shell: /usr/sbin/subscription-manager repos --enable {{ item }}
      with_items: repos
    - name: install support packages
      yum:
        name: "{{ item }}"
        state: present
        enablerepo: "{{repo_list}}"
      with_items: packages
    - name: selinux
      selinux: 
        policy: targeted 
        state: permissive
