    - name: NFS Mountpoint
      file:
        path: "/var/opt/rh/rh-postgresql94/lib/pgsql/wal-archive"
        state: directory
        owner: postgres
        group: postgres
        mode: u=rwx,g=,o=
    - name: NFS Mount Configuration
      mount:
        name: /var/opt/rh/rh-postgresql94/lib/pgsql/wal-archive
        src: "{{ nfs_path }}"
        fstype: nfs
        opts: defaults
        state: mounted
    - name: NFS Subdir for this cluster
      file:
        path: "/var/opt/rh/rh-postgresql94/lib/pgsql/wal-archive/{{pgClusterName}}"
        state: directory
        owner: postgres
        group: postgres
        mode: u=rwx,g=,o=
      when: ansible_hostname == cluster_master        
